# INSERT INTO `users` (`id`, `email`, `first_name`, `last_name`, `password`, `username`)
# VALUES
#     (1, 'admin@email.com', 'admin', 'admin', 'f292ad79a41b8c2240891d1adad3afdad1671fa55f463b1c20ad992d822fe031f1fd3b7f34419ac4b7f49f978279725e', 'admin'),
#     (2, 'greta@email.com', 'Greta', 'Marinova', 'eba54a5352e9fb178a2a464af2f60355da8e0c53e8ecf69500d133f61570b1004cdaa493d5191f4b4438c15f60caf1e5', 'greta'),
#     (7, 'toni@email.com', 'Antoaneta', 'Antoaneta', '9322cff1b5252a14b81ccf972ab6f038ddbdf36a67defaab63d6b817beb701191c05b858429fda603eaee7b6d5079a76', 'toni'),
#     (8, 'mustaka64@email.com', 'Yordan', 'Yordan', 'dd86672766be3db18aaa14ae352753bd62c72851bb52d78a6a1a84c580f476a4be7bb22399f23cfef63d65b65e5bcd1a', 'mustaka64'),
#     (12, 'stilyanov@email.com', 'Vladimir', 'Stilyanov', 'b8d0031f95a548ff863145a5a33204f4372bd33a6ea78e8981b793c0db52ec0d6fe92f9df9c4dc9686d64fcd58de5b9e', 'stilyanov');

# INSERT INTO `users_roles` (`user_id`, `role_id`)
# VALUES
#     (1, 1),
#     (2, 3),
#     (7, 3),
#     (8, 3),
#     (12, 3);

INSERT INTO `doctors` (`id`, `bio`, `experience`, `first_name`, `image_url`, `last_name`, `department_id`, `user_id`, `city`)
VALUES
    (3, 'Dr. Emily Johnson is a highly skilled cardiologist specializing in diagnosing and treating heart conditions. She is well-known for her compassionate care and her commitment to patient health. Dr. Johnson has extensive experience in managing complex cardiovascular diseases and is proficient in advanced diagnostic techniques.', 12, 'Emily', 'https://img.freepik.com/free-photo/doctor-with-white-robe-stethoscope_144627-43879.jpg', 'Johnson', 1, 1, 'Varna'),
    (4, 'Dr. Michael Smith is an expert orthopedic surgeon with a focus on sports injuries and joint replacements. He is dedicated to helping patients recover mobility and live pain-free lives. Dr. Smith is renowned for his surgical precision and his innovative approach to minimally invasive procedures.', 15, 'Michael', 'https://www.shutterstock.com/image-photo/covid19-coronavirus-outbreak-healthcare-workers-260nw-1779353891.jpg', 'Smith', 4, 1, 'Veliko Turnovo'),
    (5, 'Dr. Sarah Lee is a caring pediatrician known for her gentle approach with children and her ability to communicate effectively with parents. She specializes in preventive care, growth and development monitoring, and the management of chronic conditions in children. Dr. Lee is passionate about ensuring the well-being of her young patients.', 8, 'Sarah', 'https://assets.medpagetoday.net/media/images/73xxx/73617.jpg', 'Lee', 5, 1, 'Plovdiv'),
    (6, 'Dr. David Patel is a dermatologist who excels in treating a wide range of skin conditions, including acne, eczema, and psoriasis. He is also skilled in cosmetic dermatology, offering treatments such as Botox and laser therapy. Dr. Patel is known for his personalized care and his dedication to enhancing the health and appearance of his patients\' skin.', 10, 'David', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ482r1Wj8jqyJMpsc4GhGtJltFY4nrSkiVA&s', 'Patel', 2, 1, 'Burgas'),
    (7, 'Dr. Anna Rodriguez is a neurologist with a deep understanding of the brain and nervous system. She specializes in treating conditions such as epilepsy, multiple sclerosis, and Parkinson\'s disease. Dr. Rodriguez is committed to providing comprehensive care and support to patients and their families, ensuring the best possible outcomes.', 14, 'Anna', 'https://kandidataasia.com/wp-content/uploads/2011/10/dr.jpg', 'Rodriguez', 3, 1, 'Sofia'),
    (8, 'Dr. John Kim is a general surgeon known for his expertise in performing a wide range of surgical procedures. He is dedicated to ensuring patient safety and achieving excellent surgical outcomes. Dr. Kim is particularly skilled in laparoscopic and robotic surgeries, which offer less invasive options for patients.', 11, 'John', 'https://t4.ftcdn.net/jpg/02/60/04/09/360_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg', 'Kim', 6, 1, 'Pleven'),
    (9, 'Lisa Wang is an endocrinologist specializing in hormonal disorders, including diabetes, thyroid diseases, and metabolic disorders. She is passionate about educating patients on managing their conditions and improving their quality of life. Dr. Wang is recognized for her thorough and empathetic approach to patient care.', 9, 'Lisa', 'https://img.freepik.com/free-photo/beautiful-young-female-doctor-looking-camera-office_1301-7807.jpg?size=626&ext=jpg', 'Wang', 9, 1, 'Sofia'),
    (10, 'Dr. Robert Garcia is an oncologist dedicated to the diagnosis\r\n                    and treatment of cancer. He has a wealth of experience in chemotherapy, radiation therapy, and\r\n                    immunotherapy. Dr. Garcia is known for his compassionate patient care and his commitment to\r\n                    staying at the forefront of cancer research and treatment.', 13, 'Robert', 'https://img.freepik.com/free-photo/handsome-elderly-doctor-uniform_144627-1195.jpg?size=626&ext=jpg', 'Garcia', 8, 1, 'Pleven'),
    (11, 'pekpoqkepqopekpoqkepqopekpoqkepqopekpoqkepqopekpoqkepqopekpoqkepqo', 15, 'Greta', 'https://img.freepik.com/free-photo/beautiful-young-female-doctor-looking-camera-office_1301-7807.jpg?size=626&ext=jpg', 'Marinova', 1, 2, 'Veliko Turnovo'),
    (15, 'Dr. Emily Harper is a highly skilled cardiologist specializing in diagnosing and treating heart conditions. She is well-known for her compassionate care and her commitment to patient health. Dr. Johnson has extensive experience in managing complex cardiovascular diseases and is proficient in advanced diagnostic techniques.\r\nDr. Emily Johnson is a highly skilled cardiologist specializing in diagnosing and treating heart conditions. She is well-known for her compassionate care and her commitment to patient health. Dr. Johnson has extensive experience in managing complex cardiovascular diseases and is proficient in advanced diagnostic techniques.', 30, 'Emily', 'https://img.freepik.com/premium-photo/smiling-doctor-with-strethoscope_258943-53.jpg?size=626&ext=jpg&ga=GA1.1.1502090658.1720869845&semt=sph', 'Harper', 10, 1, 'Instanbul');